version: "2"

services:
  httpd:
    volumes:
    - ${APACHE_SSL_CERT_PATH}:/etc/ssl/app:ro
    - ${SQLDESIGNER_DATA}:/var/lib/sqldesigner
    environment:
    - APACHE_SSL
    - APACHE_SSL_KEY
    - APACHE_SSL_CERT
    - APACHE_SSL_CHAIN
    - MACHINE_HOST
    - SECURED_RESOURCE_ALLOWED_IP
    networks: 
      default:
        aliases: [proxy]
    extends:
      service: logging

  owncloud:
    extends:
      service: logging
    environment:
    - OWNCLOUD_DB_TYPE
    - OWNCLOUD_DB_NAME
    - OWNCLOUD_DB_USERNAME
    - OWNCLOUD_DB_PASSWORD
    - OWNCLOUD_DB_HOST

  mysql:
    image: mysql:5.6
    volumes:
    - ./mysql:/etc/mysql/conf.d:ro
    environment:
    - MYSQL_ROOT_PASSWORD
    networks: 
      default:
        aliases: [db, mysql]
    extends:
      service: logging

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment: 
    - MYSQL_ROOT_PASSWORD
    extends:
      service: logging

  logging:
    logging: 
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"