version: "2"

services:
  httpd:
    volumes:
    - ${APACHE_SSL_CERT_PATH}:/etc/ssl/app:ro
    environment:
    - APACHE_SSL
    - APACHE_SSL_KEY
    - APACHE_SSL_CERT
    - APACHE_SSL_CHAIN
    - MACHINE_HOST
    - SECURED_RESOURCE_ALLOWED_IP
    extends:
      service: logging

  owncloud:
    volumes:
    - ./owncloud/config.php:/var/www/html/config/config.php
    extends:
      service: logging

  mysql:
    image: mysql:5.5
    volumes:
    - ./mysql:/etc/mysql/conf.d:ro
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD
    extends:
      service: logging

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment: 
    - MYSQL_ROOT_PASSWORD
    extends:
      service: logging

  logging:
    logging: 
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"