version: "2"

services:
  
  mysql:
    extends:
      file: common-services.yml
      service: mysql
    networks: 
      default:
        aliases: [db, mysql]

  phpmyadmin:
    extends:
      file: common-services.yml
      service: phpmyadmin
    ports: 
    - 80:80