version: "2"

services:
  owncloud:
    build: owncloud
    extends:
      file: common-services.yml
      service: owncloud
    volumes:
    - ${OWNCLOUD_DATA}:/var/www/html/data
    links:
    - mysql:db
    ports:
    - 80:80

  mysql:
    extends:
      file: common-services.yml
      service: mysql
    volumes:
    - ${MYSQL_DATA}:/var/lib/mysql
    networks: 
      default:
        aliases: [db, mysql]

  phpmyadmin:
    extends:
      file: common-services.yml
      service: phpmyadmin
    ports: 
    - 8080:80