version: "2"

services:

  owncloud:
    image: ${REGISTRY_URL}/owncloud:${OWNCLOUD_VERSION}
    extends:
      file: common-services.yml
      service: owncloud
    environment: 
    - OWNCLOUD_REDIS_ENABLED=true
    - OWNCLOUD_REDIS_HOST=redis
    volumes:
    - ${OWNCLOUD_DATA}:/mnt/data
    networks: 
      default:
      hub_net:
        aliases: 
        - ${HUB_INSTANCE}
    restart: "unless-stopped"

  redis:
    image: webhippie/redis:latest
    environment:
      - REDIS_DATABASES=1
    volumes:
    - redis:/var/lib/redis
    restart: "unless-stopped"

networks: 
  hub_net:
    external: true

volumes:
  redis:
    driver: local