version: "2"

services:
  httpd:
    build: httpd
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - docker_app:/var/www
      - "/home/sangah:/home/sangah:ro"
      - /etc/letsencrypt:/etc/ssl/app:ro
      - "/var/www:/var/www/extra"
    links:
      - fileserver
    external_links:
      - was_stnd:was
    environment:
      - APACHE_SSL
      - APACHE_SSL_KEY
      - APACHE_SSL_CERT
      - APACHE_SSL_CHAIN
    restart: "unless-stopped"

  fileserver-php:
    image: php:5.6-fpm
    volumes:
      - ngx:/etc/nginx/www
    restart: "unless-stopped"

  fileserver:
    image: dev.sangah.com:5043/pmis-fileupload
    volumes:
      - ngx:/etc/nginx/www
      - /tmp:/tmp
    links:
      - fileserver-php:php
    restart: "unless-stopped"

  owncloud:
    image: owncloud:8.2.9
    volumes:
    - ./owncloud/config.php:/var/www/html/config/config.php
    - /home/cloud/data:/var/www/html/data
    links:
      - mysql:db
      - httpd:proxy
    restart: "unless-stopped"

  mysql:
    image: mysql:5.5
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./mysql:/etc/mysql/conf.d
      - /var/lib/mysql:/var/lib/mysql 
    environment:
      - MYSQL_ROOT_PASSWORD
    restart: "unless-stopped"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "18090:80"
    environment: 
      - MYSQL_ROOT_PASSWORD
    links:
      - mysql:db
    restart: "unless-stopped"
    
volumes:
  ngx:
  docker_app:
    external: true