version: "2"

services:
  owncloud:
    build: owncloud
    extends:
      file: common-services.yml
      service: owncloud
    volumes:
    - owncloud:/mnt/data
    environment:
      - OWNCLOUD_DOMAIN
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=root
      - OWNCLOUD_DB_PASSWORD=changeme
      - OWNCLOUD_DB_HOST=db
      - OWNCLOUD_ADMIN_USERNAME
      - OWNCLOUD_ADMIN_PASSWORD
      #- OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
    depends_on:
    - mysql
    ports:
    - "80"

  mysql:
    extends:
      file: common-services.yml
      service: mysql
    networks: 
      default:
        aliases: [db, mysql]
    volumes:
    - mysql:/var/lib/mysql

  phpmyadmin:
    extends:
      file: common-services.yml
      service: phpmyadmin
    ports: 
    - 80:80

  redis:
    image: webhippie/redis:latest
    restart: always
    environment:
      - REDIS_DATABASES=1
    volumes:
    - redis:/var/lib/redis

volumes:
  redis:
    driver: local
  mysql:
    driver: local
  owncloud:
    driver: local