version: "2"

services:
  owncloud:
    build: owncloud
    extends:
      file: common-services.yml
      service: owncloud
    volumes:
    - ${OWNCLOUD_DATA}:/var/www/html/data
    depends_on:
    - mysql
    ports:
    - "80"

  mysql:
    extends:
      file: common-services.yml
      service: mysql
    volumes:
    - ${MYSQL_DATA}:/var/lib/mysql
