version: "2"

services:
  httpd:
    build: httpd
    ports:
    - "80:80"
    - "443:443"
    extends: 
      file: common-services.yml
      service: httpd
    volumes:
    - /home/sangah:/home/sangah:ro
    - /etc/letsencrypt:/etc/letsencrypt:ro
    - /var/www:/var/www/html
    - ./sqldesigner:/var/www/html/sqldesigner
    - ./httpd/conf/sites-available/pmis-manual.conf:/etc/apache2/sites-enabled/pmis-manual.conf
    restart: "unless-stopped"

  owncloud:
    image: ${REGISTRY_URL}/owncloud:${OWNCLOUD_VERSION}
    extends:
      file: common-services.yml
      service: owncloud
    environment: 
    - OWNCLOUD_REDIS_ENABLED=true
    - OWNCLOUD_REDIS_HOST=redis
    volumes:
    - ${OWNCLOUD_DATA}:/mnt/data
    depends_on: 
    - httpd
    - mysql
    restart: "unless-stopped"

  redis:
    image: webhippie/redis:latest
    restart: always
    environment:
      - REDIS_DATABASES=1
    volumes:
    - redis:/var/lib/redis