version: "2"

services:
  owncloud:
    build: owncloud
    extends:
      file: common-services.yml
      service: owncloud
    volumes:
    - owncloud:/mnt/data
    environment:
    - OWNCLOUD_ADMIN_USERNAME=admin
    - OWNCLOUD_ADMIN_PASSWORD=secret
    - OWNCLOUD_REDIS_ENABLED=true
    - OWNCLOUD_REDIS_HOST=redis
    depends_on:
    - mysql
    ports:
    - "80"

  mysql:
    extends:
      file: common-services.yml
      service: mysql
    networks: 
      default:
        aliases: [db, mysql]
    volumes:
    - mysql:/var/lib/mysql

  phpmyadmin:
    extends:
      file: common-services.yml
      service: phpmyadmin
    ports: 
    - 80:80

  redis:
    image: webhippie/redis:latest
    restart: always
    environment:
      - REDIS_DATABASES=1
    volumes:
    - redis:/var/lib/redis

volumes:
  redis:
    driver: local
  mysql:
    driver: local
  owncloud:
    driver: local
