version: "2"

services:
  httpd:
    extends: 
      file: common-services.yml
      service: httpd
    volumes:
      - /home/sangah:/home/sangah:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www:/var/www/html
      - ./httpd/conf/sites-available/pmis-manual.conf:/etc/apache2/sites-enabled/pmis-manual.conf

  owncloud:
    extends:
      file: common-services.yml
      service: owncloud
    volumes:
      - /home/cloud/data:/var/www/html/data
    links:
      - mysql:db
      - httpd:proxy
    restart: "unless-stopped"

  mysql:
    extends:
      file: common-services.yml
      service: mysql
    volumes:
      - /var/lib/mysql:/var/lib/mysql 

  phpmyadmin:
    extends:
      file: common-services.yml
      service: phpmyadmin
    links:
      - mysql:db
    environment: 
      - PMA_ABSOLUTE_URI=https://dev.sangah.com/mysqladmin/