version: "2"

services:
  
  mysql:
    extends:
      file: common-services.yml
      service: mysql
    networks: 
      default:
        aliases: [db, mysql]
    volumes:
    - mysql:/var/lib/mysql

  phpmyadmin:
    extends:
      file: common-services.yml
      service: phpmyadmin
    ports: 
    - 80:80

volumes:
  mysql:
    driver: local