version: "2"

services:
  httpd:
    build: httpd
    ports:
    - "80:80"
    - "443:443"
    extends: 
      file: common-services.yml
      service: httpd
    volumes:
    - /home/sangah:/home/sangah:ro
    - /etc/letsencrypt:/etc/letsencrypt:ro
    - /var/www:/var/www/html
    - ./sqldesigner:/var/www/html/sqldesigner
    - ./httpd/conf/sites-available/pmis-manual.conf:/etc/apache2/sites-enabled/pmis-manual.conf
    restart: "unless-stopped"

  owncloud:
    image: ${REGISTRY_URL}/owncloud:0.1
    extends:
      file: common-services.yml
      service: owncloud
    volumes:
    - ${OWNCLOUD_DATA}:/var/www/html/data
    depends_on: 
    - httpd
    - mysql
    restart: "unless-stopped"

  mysql:
    extends:
      file: common-services.yml
      service: mysql
    volumes:
    - ${MYSQL_DATA}:/var/lib/mysql
    ports:
    - 3306:3306
    restart: "unless-stopped"

  phpmyadmin:
    extends:
      file: common-services.yml
      service: phpmyadmin
    environment: 
    - PMA_ABSOLUTE_URI=https://dev.sangah.com/mysqladmin/
    restart: "unless-stopped"